[package]
name = "posebench"
version = "0.1.0"
edition = "2024"

[features]
rt-ort = ["dep:ort"]
rt-tract = ["dep:tract-onnx"]

[dependencies]
v4l = "0.14.0"
ort = { version = "=2.0.0-rc.13", optional = true, default-features = false, features = ["std", "download-binaries", "tls-native", "copy-dylibs", "api-24"] }
tract-onnx = { version = "0.23.8", optional = true }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
